#!/usr/bin/env python3
"""
Spanish Translation Updater - Phase 6
Updates Spanish localization file with more translations
"""

import re
from pathlib import Path

# İspanyolca çeviriler - Phase 1 + Phase 2
TRANSLATIONS = {
    # === PHASE 1: BASICS (64 keys) ===
    
    # TAB TITLES (10)
    "tab.moodJournal": "Diario de Estado de Ánimo",
    "tab.memories": "Recuerdos",
    "tab.activities": "Actividades",
    "tab.analytics": "Análisis",
    "tab.contacts": "Amigos",
    "tab.dashboard": "Inicio",
    "tab.goals": "Objetivos",
    "tab.location": "Actividad",
    "tab.settings": "Configuración",
    "aibrain.tab.title": "Cerebro IA",

    # COMMON BUTTONS (20)
    "button.save": "Guardar",
    "button.cancel": "Cancelar",
    "button.delete": "Eliminar",
    "button.edit": "Editar",
    "button.close": "Cerrar",
    "button.ok": "Aceptar",
    "button.update": "Actualizar",
    "button.details": "Detalles",
    "button.complete": "Completar",
    "button.message": "Mensaje",
    "button.call": "Llamar",
    "button.share": "Compartir",
    "button.retry": "Reintentar",
    "button.preview": "Vista Previa",
    "button.analyze": "Iniciar Análisis",
    "button.reanalyze": "Re-analizar",
    "button.remove.photo": "Quitar Foto",
    "button.weekly.analysis": "Crear Análisis Semanal",
    "button.edit.title": "Editar Título",
    "button.view.details": "Ver Detalles",

    # NAVIGATION (15)
    "nav.daily.insight": "Tu Perspectiva Diaria",
    "nav.save.mood": "Guardar Estado de Ánimo",
    "nav.emoji.picker": "Elegir Emoji",
    "nav.add.note": "Añadir Nota",
    "nav.tags": "Etiquetas",
    "nav.frequent.tags": "Etiquetas Frecuentes",
    "nav.ai.brain": "Cerebro IA",
    "nav.ai.chat": "Chat IA",

    # LABELS (5)
    "label.ai.chat": "Chat IA",

    # PLACEHOLDERS (15)
    "placeholder.title": "Título",
    "placeholder.mood.note": "¿Qué pasó hoy?",
    "placeholder.emoji.search": "Buscar emoji...",
    "placeholder.tag.name": "Nombre de etiqueta",
    "placeholder.custom.tag": "Añadir etiqueta personalizada",
    "placeholder.etiket.ekle": "Añadir etiqueta",
    "placeholder.notes": "Tus notas...",
    "placeholder.avatar.emoji": "Emoji de Avatar",
    "placeholder.name": "Nombre",
    "placeholder.phone": "Teléfono",
    "placeholder.place.name": "Nombre del lugar",

    # ERRORS (10)
    "error.invalid.coordinates": "Coordenadas inválidas",
    "error.check.updates": "Buscar Actualizaciones",
    "error.contact.support": "Por favor contacta con soporte si el problema persiste",
    "error.restart.app": "Reiniciar Aplicación",
    "error.retry": "Reintentar",

    # MOOD (5)
    "mood.happy": "Feliz",
    "mood.sad": "Triste",
    "mood.add.tags": "Añadir etiquetas",

    # FRIENDS (3)
    "friend.notes": "Notas",

    # COMMON (15)
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.add": "Añadir",
    "common.settings": "Configuración",
    "common.back": "Atrás",
    "common.next": "Siguiente",
    "common.close": "Cerrar",
    "common.ok": "Aceptar",

    # === PHASE 2: EXPANDED CATEGORIES (200+ keys) ===
    
    # ACHIEVEMENTS (20)
    "achievement.category.consistency": "Consistencia",
    "achievement.category.goal": "Objetivos",
    "achievement.category.habit": "Hábitos",
    "achievement.category.special": "Especial",
    "achievement.first.goal.title": "Primer Objetivo",
    "achievement.first.goal.desc": "Crea tu primer objetivo",
    "achievement.first.habit.title": "Primer Hábito",
    "achievement.first.habit.desc": "Crea tu primer hábito",
    "achievement.week.warrior.title": "Guerrero Semanal",
    "achievement.week.warrior.desc": "Completa objetivos/hábitos durante 7 días consecutivos",
    "achievement.month.champion.title": "Campeón Mensual",
    "achievement.month.champion.desc": "Completa durante 30 días consecutivos",
    "achievement.hundred.master.title": "Maestro de los Cien",
    "achievement.hundred.master.desc": "Completa durante 100 días consecutivos",
    "achievement.habit.master.title": "Maestro de Hábitos",
    "achievement.habit.master.desc": "Racha de 30 días en un hábito",
    "achievement.legendary.habit.title": "Hábito Legendario",
    "achievement.legendary.habit.desc": "Racha de 90 días en un hábito",
    "achievement.goal.hunter.title": "Cazador de Objetivos",
    "achievement.health.king.title": "Rey de la Salud",
    "achievement.health.king.desc": "Completa 5 objetivos de salud",

    # ACTIVITIES (30)
    "activity.complete.button": "Completar Actividad",
    "activity.completed.alert.title": "¡Actividad Completada!",
    "activity.completed.alert.message": "¡Felicidades! ¡Ganaste %lld puntos!",
    "activity.completed.alert.button": "¡Genial!",
    "activity.detail.title": "Detalle de Actividad",
    "activity.info.title": "Información de Actividad",
    "activity.info.difficulty": "Dificultad",
    "activity.info.duration": "Duración",
    "activity.info.points": "Puntos",
    "activity.info.views": "Vistas",
    "activity.info.last_viewed": "Última Vista",
    "activity.completion.history": "Historial de Finalización",
    "activity.current.outdoor": "Al Aire Libre",
    "activity.type.creative": "Creativo",
    "activity.type.exercise": "Ejercicio",
    "activity.type.learning": "Aprendizaje",
    "activity.type.outdoor": "Al Aire Libre",
    "activity.type.relax": "Relajarse",
    "activity.type.social": "Social",
    "activity.suggestion.walk.title": "Dar un Paseo 🚶",
    "activity.suggestion.walk.desc": "Camina 30 minutos, toma aire fresco",
    "activity.suggestion.exercise.title": "Hacer Ejercicio 🏃",
    "activity.suggestion.exercise.desc": "Ve al parque cercano a correr",
    "activity.suggestion.meditation.title": "Meditar 🧘",
    "activity.suggestion.meditation.desc": "Haz 10 minutos de ejercicios de respiración",
    "activity.suggestion.cafe.title": "Ir a un Café ☕",
    "activity.suggestion.cafe.desc": "¿Qué tal un café con un amigo?",
    "activity.suggestion.creative.title": "Sé Creativo 🎨",
    "activity.suggestion.creative.desc": "Dibuja o escribe algo",
    "activity.suggestion.learn.title": "Aprende Algo Nuevo 📖",
    "activity.suggestion.learn.desc": "Inicia un curso en línea",

    # FRIENDS (15)
    "friend.add": "Añadir Amigo",
    "friend.edit": "Editar Amigo",
    "friend.delete": "Eliminar Amigo",
    "friend.achievements": "Logros",
    "friend.activities.footer": "Actividades que hacen o quieren hacer juntos (separadas por comas)",
    "friend.basic.info": "Información Básica",
    "friend.best.day.contact": "Mejor Día",
    "friend.change.emoji": "Cambiar Emoji",
    "friend.comma.separated": "Separar con comas",
    "friend.communication.frequency": "Frecuencia de Comunicación",
    "friend.last.30.days": "Últimos 30 Días",
    "friend.relationship.health": "Salud de la Relación",
    "friend.action.ai.chat": "Chat IA",
    "friend.action.mark.contacted": "Marcar Completado",

    # GOALS (25)
    "goal.achievements": "Logros",
    "goal.ai.coaching": "Coaching IA",
    "goal.all.templates": "Todas las Plantillas",
    "goal.blank.title": "Objetivo en Blanco",
    "goal.blank.description": "Empieza desde cero",
    "goal.category.career": "Carrera",
    "goal.category.education": "Educación",
    "goal.category.family": "Familia",
    "goal.category.finance": "Finanzas",
    "goal.category.fitness": "Fitness",
    "goal.category.health": "Salud",
    "goal.category.hobby": "Pasatiempo",
    "goal.category.home": "Hogar",
    "goal.category.personal": "Personal",
    "goal.category.relationship": "Relaciones",
    "goal.category.social": "Social",
    "goal.category.travel": "Viajes",
    "goal.category.work": "Trabajo",
    "goal.daily": "Diario",
    "goal.weekly": "Semanal",
    "goal.monthly": "Mensual",
    "goal.new": "Nuevo Objetivo",
    "goal.title": "Objetivo",
    "goal.ai.generating": "IA generando descripción...",
    "goal.basic.info.description": "Establece el título y categoría de tu objetivo",

    # HABITS (15)
    "habit.blank.title": "Hábito en Blanco",
    "habit.blank.description": "Empieza desde cero",
    "habit.daily": "Diario",
    "habit.weekly": "Semanal",
    "habit.monthly": "Mensual",
    "habit.new": "Nuevo Hábito",
    "habit.title": "Hábito",
    "habit.description.optional": "Descripción (Opcional)",
    "habit.error.name.empty": "El nombre del hábito no puede estar vacío",
    "habit.target.count": "Cuenta Objetivo",
    "habit.ai.generating": "IA está generando descripción...",
    "habit.ai.suggestion": "Sugerencia IA",
    "habit.basic.info.description": "Establece el nombre y frecuencia de tu hábito",
    "habit.error.name.too.long": "El nombre del hábito es demasiado largo",
    "habit.error.description.too.long": "La descripción del hábito es demasiado larga",
    
    # MOOD EXPANDED (15)
    "mood.great": "Genial",
    "mood.good": "Bien",
    "mood.okay": "Normal",
    "mood.notGreat": "No Muy Bien",
    "mood.analytics.highlights": "Destacados",
    "mood.analytics.pattern": "Patrón",
    "mood.analytics.suggestions": "Sugerencias",
    "mood.analytics.detailed.analysis": "Análisis Detallado",
    "mood.ai.analysis.ready": "Análisis IA Listo",
    "mood.30.day.heatmap": "Mapa de Calor de 30 Días",
    "mood.30plus.analysis": "Análisis de 30+ Días",
    "mood.correlation.empty.message": "Rastrea tus estados de ánimo para ver correlaciones con amigos, objetivos y ubicaciones",
    
    # COMMON UI (20)
    "today": "Hoy",
    "yesterday": "Ayer",
    "tomorrow": "Mañana",
    "this.week": "Esta Semana",
    "this.month": "Este Mes",
    "all": "Todos",
    "none": "Ninguno",
    "loading": "Cargando...",
    "saving": "Guardando...",
    "success": "Éxito",
    "failed": "Fallido",
    "completed": "Completado",
    "pending": "Pendiente",
    "active": "Activo",
    "inactive": "Inactivo",
    "start": "Comenzar",
    "stop": "Detener",
    "pause": "Pausar",
    "resume": "Reanudar",
    "continue": "Continuar",

    # === PHASE 3: EXPANDED FEATURES (140+ keys) ===

    # SETTINGS (30)
    "settings.title": "Configuración",
    "settings.general.settings": "Configuración General",
    "settings.notifications.title": "Notificaciones",
    "settings.notifications.permission": "Permiso de Notificaciones",
    "settings.notifications.permission.desc": "Permitir notificaciones para recordatorios",
    "settings.notifications.types": "Tipos de Notificaciones",
    "settings.notifications.friend.reminders": "Recordatorios de Amigos",
    "settings.notifications.goal.reminders": "Recordatorios de Objetivos",
    "settings.notifications.habit.reminders": "Recordatorios de Hábitos",
    "settings.notifications.quiet.hours": "Horas Silenciosas",
    "settings.language": "Idioma",
    "settings.language.change.title": "Cambiar Idioma",
    "settings.language.change.button": "Cambiar Idioma",
    "settings.appearance.profile": "Apariencia y Perfil",
    "settings.privacy": "Privacidad",
    "settings.privacy.policy": "Política de Privacidad",
    "settings.terms.of.use": "Términos de Uso",
    "settings.about.title": "Acerca de",
    "settings.version": "Versión",
    "settings.data.management.title": "Gestión de Datos",
    "settings.data.export": "Exportar Datos",
    "settings.data.restore.backup": "Restaurar Copia de Seguridad",
    "settings.delete.all.data": "Eliminar Todos los Datos",
    "settings.delete.warning": "Esta acción no se puede deshacer",
    "settings.location.title": "Ubicación",
    "settings.location.permission": "Permiso de Ubicación",
    "settings.location.permission.desc": "Permitir acceso a tu ubicación",
    "settings.ai.features": "Características de IA",
    "settings.ai.privacy.settings": "Configuración de Privacidad de IA",
    "settings.premium.title": "Premium",
    "settings.premium.upgrade": "Actualizar a Premium",

    # LOCATION (30)
    "location.history": "Historial de Ubicación",
    "location.saved.places.empty": "No hay lugares guardados",
    "location.current": "Ubicación Actual",
    "location.home.location.set": "Establecer como Casa",
    "location.place.name": "Nombre del Lugar",
    "location.place.category": "Categoría del Lugar",
    "location.place.notes.optional": "Notas (Opcional)",
    "location.place.emoji": "Emoji del Lugar",
    "location.place.radius": "Radio del Lugar",
    "location.place.saved.message": "Lugar guardado exitosamente",
    "location.visits.count": "Número de Visitas",
    "location.recent.visits": "Visitas Recientes",
    "location.total.distance": "Distancia Total",
    "location.record.count": "Registros",
    "location.type.home": "Casa",
    "location.type.work": "Trabajo",
    "location.type.outside": "Fuera",
    "location.unknown": "Desconocido",
    "location.at.place": "En este lugar",
    "location.not.at.saved.place": "No en lugar guardado",
    "location.radius.meters": "Radio (metros)",
    "location.information": "Información",
    "location.tracking.info": "Información de Seguimiento",
    "location.my.favorites": "Mis Favoritos",
    "location.what.to.do": "Qué Hacer Aquí",
    "location.badges": "Insignias",
    "location.points": "Puntos",
    "location.ongoing": "En Curso",
    "location.delete.confirm": "¿Eliminar este lugar?",
    "location.place.basic.info": "Información Básica",
    "location.stay.duration": "Duración de Estancia",

    # PROFILE (20)
    "profile.my.profile": "Mi Perfil",
    "profile.my.info": "Mi Información",
    "profile.name": "Nombre",
    "profile.name.placeholder": "Tu nombre",
    "profile.age": "Edad",
    "profile.occupation": "Ocupación",
    "profile.occupation.placeholder": "Tu ocupación",
    "profile.basic.info": "Información Básica",
    "profile.about": "Acerca de",
    "profile.interests": "Intereses",
    "profile.hobbies": "Pasatiempos",
    "profile.core.values": "Valores Fundamentales",
    "profile.life.goals": "Metas de Vida",
    "profile.work.schedule": "Horario de Trabajo",
    "profile.living.arrangement": "Situación de Vivienda",
    "profile.add.interest": "Agregar Interés",
    "profile.add.hobby": "Agregar Pasatiempo",
    "profile.add.value": "Agregar Valor",
    "profile.saved": "Guardado",
    "profile.saved.message": "Perfil guardado exitosamente",

    # PREMIUM (20)
    "premium.title": "Premium",
    "premium.subtitle": "Desbloquea todas las funciones",
    "premium.upgrade": "Actualizar a Premium",
    "premium.upgrade.button": "Actualizar Ahora",
    "premium.label": "Premium",
    "premium.badge.title": "Miembro Premium",
    "premium.trial.3days": "Prueba de 3 Días",
    "premium.trial.info": "Prueba gratis durante 3 días",
    "premium.trial.active": "Prueba Activa",
    "premium.trial.days.remaining": "días restantes",
    "premium.monthly.subscription": "Suscripción Mensual",
    "premium.per.month": "por mes",
    "premium.plan.monthly": "Plan Mensual",
    "premium.plan.yearly": "Plan Anual",
    "premium.period.month": "mes",
    "premium.period.year": "año",
    "premium.savings.yearly": "Ahorra 20% con el plan anual",
    "premium.cancel.anytime": "Cancela en cualquier momento",
    "premium.restore.purchases": "Restaurar Compras",
    "premium.unlimited.usage": "Uso Ilimitado",

    # NOTIFICATIONS (20)
    "notification.center.empty.title": "Sin Notificaciones",
    "notification.center.empty.message": "No tienes notificaciones nuevas",
    "notification.group.today": "Hoy",
    "notification.group.yesterday": "Ayer",
    "notification.group.this.week": "Esta Semana",
    "notification.group.older": "Más Antiguas",
    "notification.mark.all.read": "Marcar Todas como Leídas",
    "notification.clear.all": "Borrar Todas",
    "notification.contact.reminder.title": "Recordatorio de Contacto",
    "notification.contact.reminder.body": "Es hora de contactar a tu amigo",
    "notification.goal.reminder.title": "Recordatorio de Objetivo",
    "notification.habit.reminder.title": "Recordatorio de Hábito",
    "notification.daily.activity.title": "Actividad Diaria",
    "notification.weekly.summary.title": "Resumen Semanal",
    "notification.motivation.title": "Mensaje Motivacional",
    "notification.go.outside.title": "Sal al Aire Libre",
    "notification.contact.time.title": "Hora de Contactar",
    "notification.contact.saved.title": "Contacto Guardado",
    "dashboard.notifications.title": "Notificaciones",
    "dashboard.notifications.show.all": "Ver Todas",

    # TIME & DATE (15)
    "today": "Hoy",
    "yesterday": "Ayer",
    "tomorrow": "Mañana",
    "this.week": "Esta Semana",
    "this.month": "Este Mes",
    "time.morning": "Mañana",
    "time.afternoon": "Tarde",
    "time.evening": "Noche",
    "time.night": "Madrugada",
    "time.all_day": "Todo el Día",
    "duration.days": "días",
    "duration.months": "meses",
    "duration.years": "años",
    "date.idea.romantic.picnic.title": "Picnic Romántico",
    "date.idea.cultural.museum.title": "Visita al Museo",

    # ANALYTICS (15)
    "analytics.main.title": "Análisis",
    "analytics.section.overview": "Resumen General",
    "analytics.section.mood": "Estado de Ánimo",
    "analytics.section.goals": "Objetivos",
    "analytics.section.habits": "Hábitos",
    "analytics.section.social": "Social",
    "analytics.section.location": "Ubicación",
    "analytics.timeRange.week": "Semana",
    "analytics.timeRange.month": "Mes",
    "analytics.timeRange.threeMonths": "3 Meses",
    "analytics.timeRange.year": "Año",
    "analytics.overview.wellness.excellent": "Excelente",
    "analytics.overview.wellness.good": "Bueno",
    "analytics.overview.wellness.average": "Promedio",
    "analytics.overview.wellness.poor": "Pobre",

    # === PHASE 4: CORE FEATURES (197 keys) ===

    # JOURNAL (30)
    "journal.navigation.title": "Diario",
    "journal.add.title": "Añadir Entrada",
    "journal.edit.title": "Editar Entrada",
    "journal.placeholder.title": "Título (opcional)",
    "journal.content": "Contenido",
    "journal.content.label": "Escribe tu entrada...",
    "journal.search.placeholder": "Buscar entradas...",
    "journal.empty.title": "Sin Entradas",
    "journal.empty.message": "Comienza a escribir tu primer diario",
    "journal.count": "entradas",
    "journal.reading.time": "Tiempo de lectura",
    "journal.reading.time.format": "%d min",
    "journal.word.count": "Palabras",
    "journal.word.count.label": "Contador de palabras",
    "journal.favorite": "Favorito",
    "journal.unfavorite": "Quitar de favoritos",
    "journal.delete": "Eliminar entrada",
    "journal.updated": "Actualizado",
    "journal.type": "Tipo de entrada",
    "journal.type.instruction": "Elige el tipo de entrada",
    "journal.type.question": "Entrada de pregunta",
    "journal.type.pills": "Entrada rápida",
    "journal.guided.writing.desc": "Escritura guiada con indicaciones",
    "journal.markdown": "Formato Markdown soportado",
    "journal.preview.save": "Vista previa y guardar",
    "journal.character.count": "caracteres",
    "journal.tags": "Etiquetas",
    "journal.photo.label": "Fotos",
    "journal.select.photo": "Seleccionar foto",
    "journal.calendar.day": "Día",

    # MEMORIES (25)
    "memories.empty.title": "Sin Recuerdos",
    "memories.empty.message": "Comienza a crear tus recuerdos especiales",
    "memories.create": "Crear Recuerdo",
    "memories.add.title": "Añadir Recuerdo",
    "memories.add.subtitle": "Captura momentos especiales",
    "memories.untitled": "Sin título",
    "memories.friends": "Amigos en este recuerdo",
    "memories.delete.confirm": "¿Eliminar este recuerdo?",
    "memories.private.empty.title": "Sin Recuerdos Privados",
    "memories.private.empty.message": "Crea recuerdos solo para ti",
    "memories.private.create": "Crear Recuerdo Privado",
    "memories.private.detail": "Detalles del recuerdo privado",
    "memory.untitled": "Sin título",
    "memory.save": "Guardar",
    "memory.saving": "Guardando...",
    "memory.close": "Cerrar",
    "memory.location": "Ubicación",
    "memory.tags": "Etiquetas",
    "memory.notes": "Notas",
    "memory.date.today": "Hoy",
    "memory.date.yesterday": "Ayer",
    "memory.date.this.week": "Esta semana",
    "memory.photo.count": "fotos",
    "memory.friends.count": "amigos",
    "memory.favorite": "Marcar como favorito",

    # DASHBOARD (30)
    "dashboard.todays.mood": "Estado de ánimo de hoy",
    "dashboard.add.mood": "Añadir estado de ánimo",
    "dashboard.morning.insight": "Perspectiva matutina",
    "dashboard.smart.suggestions": "Sugerencias inteligentes",
    "dashboard.statistics": "Estadísticas",
    "dashboard.achievements.title": "Logros",
    "dashboard.achievements.all": "Ver todos",
    "dashboard.log.contact": "Registrar contacto",
    "dashboard.action.write.journal": "Escribir diario",
    "dashboard.action.new.goal": "Nuevo objetivo",
    "dashboard.action.new.habit": "Nuevo hábito",
    "dashboard.stats.today": "Hoy",
    "dashboard.stats.this.week": "Esta semana",
    "dashboard.stats.communication": "Comunicación",
    "dashboard.stats.goals": "Objetivos",
    "dashboard.stats.habits": "Hábitos",
    "dashboard.stats.locations.format": "%d lugares visitados",
    "dashboard.stats.weekly.format": "%d esta semana",
    "dashboard.stats.overdue.format": "%d vencidos",
    "dashboard.streak.days.format": "%d días de racha",
    "dashboard.best.streak.format": "Mejor racha: %d días",
    "dashboard.score": "Puntuación",
    "dashboard.stats.score": "Puntuación total",
    "dashboard.stats.completion": "Tasa de finalización",
    "dashboard.time.to.go.out": "Hora de salir",
    "dashboard.hours.at.home.format": "%d horas en casa",
    "dashboard.stats.mobility": "Movilidad",
    "dashboard.more.achievements": "Más logros",
    "dashboard.achievement.progress": "Progreso de logros",
    "dashboard.contact.search.placeholder": "Buscar contacto...",

    # AI FEATURES & CHAT (40)
    "ai.chat": "Chat IA",
    "ai.insight": "Perspectiva IA",
    "ai.suggestion": "Sugerencia",
    "ai.analysis": "Análisis",
    "ai.analyzing": "Analizando...",
    "ai.thinking": "Pensando...",
    "ai.error": "Error de IA",
    "ai.back": "Volver",
    "ai.clear": "Limpiar",
    "ai.see.details": "Ver detalles",
    "ai.chat.input.placeholder": "Escribe tu mensaje...",
    "ai.chat.clear": "Limpiar chat",
    "ai.chat.share": "Compartir conversación",
    "ai.chat.assistant": "Asistente",
    "ai.user": "Usuario",
    "ai.chat.me": "Yo",
    "ai.chat.try": "Prueba a preguntar:",
    "ai.chat.to.learn": "para aprender más sobre ti",
    "ai.chat.enable.instruction": "Habilita las características de IA en ajustes",
    "ai.features.disabled": "Características de IA deshabilitadas",
    "ai.morning.insight": "Perspectiva matutina",
    "ai.analyzing.mood": "Analizando tu estado de ánimo...",
    "ai.data.usage": "Uso de datos",
    "ai.data.last.request": "Última solicitud",
    "ai.data.mood": "Datos de estado de ánimo",
    "ai.data.location": "Datos de ubicación",
    "ai.privacy.notes": "Notas de privacidad",
    "ai.privacy.note.1": "Tus datos se procesan de forma segura",
    "ai.privacy.note.2": "No compartimos información personal",
    "ai.privacy.note.3": "Puedes eliminar tus datos en cualquier momento",
    "ai.consent.title": "Consentimiento de IA",
    "ai.consent.description": "Permite que la IA aprenda de tus patrones",
    "ai.consent.shared.data": "Datos compartidos",
    "ai.consent.features.header": "Características habilitadas",
    "ai.consent.not.now": "Ahora no",
    "ai.abbr": "IA",
    "ai.active": "IA activa",
    "ai.doesnt.know.you": "La IA aún no te conoce",
    "ai.learned.info": "Información aprendida",
    "ai.categories": "Categorías",

    # ANALYTICS PATTERNS (40)
    "analytics.mood.title": "Estado de Ánimo",
    "analytics.mood.averageMood": "Estado de ánimo promedio",
    "analytics.mood.bestDay": "Mejor día",
    "analytics.mood.worstDay": "Peor día",
    "analytics.mood.consistency": "Consistencia",
    "analytics.mood.distribution": "Distribución",
    "analytics.mood.triggers": "Desencadenantes",
    "analytics.mood.no.data": "Sin datos de estado de ánimo",
    "analytics.mood.add.prompt": "Añade estados de ánimo para ver análisis",
    "analytics.social.title": "Social",
    "analytics.social.totalContacts": "Total de contactos",
    "analytics.social.mostContacted": "Más contactado",
    "analytics.social.responseRate": "Tasa de respuesta",
    "analytics.social.weeklyTrend": "Tendencia semanal",
    "analytics.social.needsAttention": "Necesita atención",
    "analytics.social.active": "Activo",
    "analytics.average.mood": "Estado de ánimo promedio",
    "analytics.daily.distribution": "Distribución diaria",
    "analytics.hourly.distribution": "Distribución por hora",
    "analytics.weekday": "Día de la semana",
    "analytics.weekday.monday": "Lunes",
    "analytics.weekday.tuesday": "Martes",
    "analytics.weekday.wednesday": "Miércoles",
    "analytics.weekday.thursday": "Jueves",
    "analytics.weekday.friday": "Viernes",
    "analytics.weekday.saturday": "Sábado",
    "analytics.weekday.sunday": "Domingo",
    "analytics.weekend": "Fin de semana",
    "analytics.weekend.count": "fines de semana",
    "analytics.weekday.count": "días laborables",
    "analytics.correlation.strong": "Fuerte",
    "analytics.correlation.moderate": "Moderado",
    "analytics.correlation.weak": "Débil",
    "analytics.correlation.veryWeak": "Muy débil",
    "analytics.correlation.veryStrong": "Muy fuerte",
    "analytics.correlation.noData": "Sin datos",
    "analytics.chart.date": "Fecha",
    "analytics.chart.value": "Valor",
    "analytics.chart.average": "Promedio",
    "analytics.chart.noData": "Sin datos disponibles",
    "analytics.congratulations": "¡Felicitaciones!",

    # MORE SETTINGS (32)
    "settings.notifications.detailed": "Notificaciones detalladas",
    "settings.notifications.types.description": "Personaliza qué notificaciones recibir",
    "settings.notifications.friend.reminders.description": "Recordatorios para contactar amigos",
    "settings.notifications.goal.reminders.description": "Recordatorios para objetivos pendientes",
    "settings.notifications.habit.reminders.description": "Recordatorios para completar hábitos",
    "settings.notifications.quiet.hours.enable": "Habilitar horas silenciosas",
    "settings.notifications.quiet.active.description": "Sin notificaciones durante estas horas",
    "settings.notifications.quiet.inactive.description": "Las notificaciones funcionan normalmente",
    "settings.notifications.start.time": "Hora de inicio",
    "settings.notifications.end.time": "Hora de finalización",
    "settings.ai.chat.settings": "Configuración de Chat IA",
    "settings.ai.chat.description": "Personaliza tu experiencia de chat con IA",
    "settings.ai.data.sharing": "Compartir datos",
    "settings.ai.data.about": "Acerca del uso de datos",
    "settings.ai.enable.features": "Habilitar características de IA",
    "settings.ai.features.active": "Características activas",
    "settings.ai.features.inactive": "Características inactivas",
    "settings.ai.features.give.consent": "Dar consentimiento",
    "settings.ai.revoke.consent": "Revocar consentimiento",
    "settings.ai.context.mode": "Modo de contexto",
    "settings.ai.smart.mode.description": "Comparte contexto relevante automáticamente",
    "settings.location.features": "Características de ubicación",
    "settings.location.management": "Gestión de ubicación",
    "settings.location.privacy.info": "Información de privacidad de ubicación",
    "settings.location.significant.changes": "Solo cambios significativos",
    "settings.battery.optimization": "Optimización de batería",
    "settings.home.location.set": "Establecer ubicación de casa",
    "settings.home.location.current": "Usar ubicación actual",
    "settings.home.radius.meters": "Radio de casa (metros)",
    "settings.app.permissions": "Permisos de la aplicación",
    "settings.permissions.title": "Permisos",
    "settings.permissions.detail.title": "Detalles de permisos",

    # === PHASE 5: DETAILED FEATURES (201 keys) ===

    # CONTACT DETAILS (40)
    "contact.frequency.daily": "Diario",
    "contact.frequency.daily.short": "Diario",
    "contact.frequency.daily.description": "Todos los días",
    "contact.frequency.twoDays": "Cada dos días",
    "contact.frequency.twoDays.short": "2 días",
    "contact.frequency.twoDays.description": "Cada 2 días",
    "contact.frequency.threeDays": "Cada tres días",
    "contact.frequency.threeDays.short": "3 días",
    "contact.frequency.threeDays.description": "Cada 3 días",
    "contact.frequency.weekly": "Semanal",
    "contact.frequency.weekly.short": "Semanal",
    "contact.frequency.weekly.description": "Una vez por semana",
    "contact.frequency.biweekly": "Quincenal",
    "contact.frequency.biweekly.short": "Quincenal",
    "contact.frequency.biweekly.description": "Cada dos semanas",
    "contact.frequency.monthly": "Mensual",
    "contact.frequency.monthly.short": "Mensual",
    "contact.frequency.monthly.description": "Una vez al mes",
    "contact.frequency.quarterly": "Trimestral",
    "contact.frequency.quarterly.short": "Trimestral",
    "contact.frequency.quarterly.description": "Cada tres meses",
    "contact.frequency.yearly": "Anual",
    "contact.frequency.yearly.short": "Anual",
    "contact.frequency.yearly.description": "Una vez al año",
    "contact.channel.phone": "Teléfono",
    "contact.channel.message": "Mensaje",
    "contact.channel.email": "Correo electrónico",
    "contact.channel.video": "Video llamada",
    "contact.channel.inPerson": "En persona",
    "contact.mood.great": "Excelente",
    "contact.mood.good": "Bueno",
    "contact.mood.okay": "Normal",
    "contact.mood.notGreat": "No muy bien",
    "contact.log.navigation.title": "Registrar contacto",
    "quick.contact.date": "Fecha",
    "quick.contact.quality": "Calidad",
    "quick.contact.notes.optional": "Notas (opcional)",
    "quick.contact.never": "Nunca",
    "quick.contact.no.friend": "Sin amigo",
    "quick.contact.change": "Cambiar",
    "quick.contact.days.ago.format": "hace %d días",

    # ONBOARDING (25)
    "onboarding.lets.start": "Comencemos",
    "onboarding.skip": "Omitir",
    "onboarding.later": "Más tarde",
    "onboarding.skip.stay.free": "Omitir y mantener gratis",
    "onboarding.ai.one.more.thing": "Una cosa más...",
    "onboarding.ai.improve.life": "Mejora tu vida con IA",
    "onboarding.ai.enable": "Habilitar IA",
    "onboarding.ai.not.now": "Ahora no",
    "onboarding.ai.chat.description": "Chatea con IA sobre tu vida",
    "onboarding.ai.morning.insight.description": "Recibe perspectivas matutinas personalizadas",
    "onboarding.privacy": "Privacidad",
    "onboarding.terms.privacy": "Términos y Privacidad",
    "onboarding.premium.title": "Premium",
    "onboarding.premium.subtitle": "Desbloquea todas las características",
    "onboarding.location.always.hint": "Selecciona 'Siempre'",
    "onboarding.location.always.instruction": "Para obtener mejores sugerencias, selecciona 'Siempre' para el permiso de ubicación",
    "settings.permission.contacts.title": "Contactos",
    "settings.permission.contacts.desc": "Acceso a tus contactos",
    "settings.permission.location.title": "Ubicación",
    "settings.permission.location.desc": "Acceso a tu ubicación",
    "settings.permission.notifications.title": "Notificaciones",
    "settings.permission.notifications.desc": "Enviar notificaciones",
    "settings.open.app.settings": "Abrir Ajustes de la App",
    "settings.location.open.settings": "Abrir Ajustes de Ubicación",
    "settings.notifications.open.settings": "Abrir Ajustes de Notificaciones",

    # APPEARANCE (15)
    "appearance.title": "Apariencia",
    "appearance.theme.header": "Tema",
    "appearance.theme.light": "Claro",
    "appearance.theme.dark": "Oscuro",
    "appearance.theme.auto": "Automático",
    "appearance.theme.description.light": "Tema claro",
    "appearance.theme.description.dark": "Tema oscuro",
    "appearance.theme.description.auto": "Sigue el sistema",
    "appearance.profile.header": "Perfil",
    "appearance.profile.default.name": "Usuario",
    "appearance.avatar.header": "Avatar",
    "appearance.avatar.change": "Cambiar Avatar",
    "appearance.language.success.message": "Idioma cambiado exitosamente",
    "settings.language.restart.warning": "Reiniciar requerido",
    "settings.language.restart.message": "La aplicación se reiniciará para aplicar el cambio de idioma",

    # API USAGE (15)
    "api.usage.stats.title": "Estadísticas de uso de API",
    "api.usage.today": "Hoy",
    "api.usage.this.hour": "Esta hora",
    "api.usage.total.requests": "Total de solicitudes",
    "api.usage.input.tokens": "Tokens de entrada",
    "api.usage.output.tokens": "Tokens de salida",
    "api.usage.estimated.cost": "Costo estimado",
    "api.usage.daily.limit": "Límite diario",
    "api.usage.remaining.quota": "Cuota restante",
    "api.usage.reset.rate.limit": "Restablecer límite de tasa",
    "api.usage.reset.cost.stats": "Restablecer estadísticas de costo",
    "api.usage.claude.pricing": "Precios de Claude",
    "settings.api.daily.usage": "Uso diario",
    "settings.api.hourly.usage": "Uso por hora",
    "settings.api.all.time.stats": "Estadísticas de todos los tiempos",

    # KNOWLEDGE (25)
    "knowledge.search.placeholder": "Buscar conocimiento...",
    "knowledge.category.personalInfo": "Información personal",
    "knowledge.category.preferences": "Preferencias",
    "knowledge.category.goals": "Objetivos",
    "knowledge.category.habits": "Hábitos",
    "knowledge.category.relationships": "Relaciones",
    "knowledge.category.values": "Valores",
    "knowledge.category.lifestyle": "Estilo de vida",
    "knowledge.category.challenges": "Desafíos",
    "knowledge.category.triggers": "Desencadenantes",
    "knowledge.category.fears": "Miedos",
    "knowledge.category.memories": "Recuerdos",
    "knowledge.category.experiences": "Experiencias",
    "knowledge.category.currentSituation": "Situación actual",
    "knowledge.category.recentEvents": "Eventos recientes",
    "knowledge.category.other": "Otro",
    "knowledge.confidence.high": "Alta",
    "knowledge.confidence.medium": "Media",
    "knowledge.confidence.low": "Baja",
    "knowledge.source.userTold": "Usuario informó",
    "knowledge.source.aiExtracted": "IA extrajo",
    "knowledge.source.inferred": "Inferido",
    "knowledge.source.pattern": "Patrón detectado",
    "knowledge.sort": "Ordenar",
    "knowledge.ai.brain.settings": "Configuración del Cerebro IA",
    "ai.knowledge.delete.warning": "¿Eliminar esta información?",

    # MORE MOOD (30)
    "mood.label": "Estado de ánimo",
    "mood.todays.mood": "Estado de ánimo de hoy",
    "mood.how.are.you.feeling": "¿Cómo te sientes?",
    "mood.how.are.you.today": "¿Cómo estás hoy?",
    "mood.how.feeling": "¿Cómo te sientes?",
    "mood.tap.to.record": "Toca para registrar",
    "mood.start.tracking": "Comenzar seguimiento",
    "mood.start.adding": "Comenzar a añadir",
    "mood.first.prompt": "¿Cómo te sientes hoy?",
    "mood.whats.happening.placeholder": "¿Qué está pasando?",
    "mood.note.optional": "Nota (opcional)",
    "mood.intensity": "Intensidad",
    "mood.intensity.label": "Intensidad del estado de ánimo",
    "mood.intensity.of.five": "de 5",
    "mood.with.intensity": "con intensidad",
    "mood.delete": "Eliminar",
    "mood.delete.mood": "Eliminar estado de ánimo",
    "mood.delete.confirmation": "¿Eliminar este registro de estado de ánimo?",
    "mood.edit": "Editar",
    "mood.edit.mood": "Editar estado de ánimo",
    "mood.more.options": "Más opciones",
    "mood.more.tags": "Más etiquetas",
    "mood.timeline": "Línea de tiempo",
    "mood.statistics": "Estadísticas",
    "mood.recommendations": "Recomendaciones",
    "mood.patterns.detected": "Patrones detectados",
    "mood.trend": "Tendencia",
    "mood.daily.streak": "Racha diaria",
    "mood.previous.records": "Registros anteriores",
    "mood.no.records": "Sin registros",
    "mood.no.records.yet": "Sin registros aún",

    # MORE ACTIVITIES (51)
    "activity.type.exercise": "Ejercicio",
    "activity.type.creative": "Creativo",
    "activity.type.relax": "Relajación",
    "activity.type.social": "Social",
    "activity.type.learning": "Aprendizaje",
    "activity.type.outdoor": "Al aire libre",
    "activity.suggestion.walk.desc": "Camina 30 minutos, toma aire fresco",
    "activity.suggestion.exercise.desc": "Ve al parque cercano a correr",
    "activity.suggestion.meditation.desc": "Haz 10 minutos de ejercicios de respiración",
    "activity.suggestion.cafe.desc": "¿Qué tal un café con un amigo?",
    "activity.suggestion.creative.desc": "Dibuja o escribe algo",
    "activity.suggestion.learn.desc": "Inicia un curso en línea",
    "activity.suggestion.bookstore.title": "Ir a una Librería 📚",
    "activity.suggestion.bookstore.desc": "Explora nuevos libros",
    "activity.suggestion.shopping.title": "Salir de Compras 🛍️",
    "activity.suggestion.shopping.desc": "Ve al centro comercial",
    "activity.info.difficulty": "Dificultad",
    "activity.info.duration": "Duración",
    "activity.info.points": "Puntos",
    "activity.info.views": "Vistas",
    "activity.info.last_viewed": "Última vista",
    "activity.completion.history": "Historial de finalización",
    "activity.completed.alert.title": "¡Actividad completada!",
    "activity.completed.alert.message": "¡Felicidades! ¡Ganaste %lld puntos!",
    "activity.completed.alert.button": "¡Genial!",
    "activity.complete.button": "Completar actividad",
    "activity.detail.title": "Detalle de actividad",
    "activity.info.title": "Información de actividad",
    "activity.current.outdoor": "Al aire libre",
    "activity.source.ai": "IA",
    "activity.source.locationBased": "Basado en ubicación",
    "activity.source.friendBased": "Basado en amigos",
    "activity.source.goalBased": "Basado en objetivos",
    "activity.source.ruleBased": "Basado en reglas",
    "activity.why.important": "Por qué es importante",
    "activity.points.remaining.format": "%d puntos restantes",
    "activity.streak.days.format": "Racha de %d días",
    "activity.noDuration": "Sin duración",
    "activity.notDone": "No completado",
    "difficulty.easy": "Fácil",
    "difficulty.medium": "Medio",
    "difficulty.hard": "Difícil",
    "difficulty.unknown": "Desconocido",
    "activity.home.start.day.title": "Comenzar el día",
    "activity.home.start.day.desc": "Planifica tu día",
    "activity.home.write.journal.title": "Escribir diario",
    "activity.home.write.journal.desc": "Reflexiona sobre tu día",
    "activity.home.review.goals.title": "Revisar objetivos",
    "activity.home.review.goals.desc": "Revisa tu progreso",
    "activity.home.connect.friends.title": "Conectar con amigos",
    "activity.home.connect.friends.desc": "Contacta a un amigo",
    "search.activities": "Buscar actividades",

    # === PHASE 5.1: ACHIEVEMENT DETAILS (13 keys - reach 700!) ===
    "achievement.all.title": "Todos los Logros",
    "achievement.awesome": "¡Increíble!",
    "achievement.completion.percentage": "Porcentaje de finalización",
    "achievement.current.progress": "Progreso actual",
    "achievement.detail.title": "Detalle del logro",
    "achievement.next": "Siguiente",
    "achievement.pagination.format": "%d de %d",
    "achievement.points.format": "%d puntos",
    "achievement.progress.fraction": "%d/%d",
    "achievement.progress.percentage": "%d%%",
    "achievement.requirement": "Requisito",
    "achievement.search.placeholder": "Buscar logros...",
    "achievement.unlocked": "Desbloqueado",

    # === PHASE 6: COMPREHENSIVE FEATURES (300 keys - reach 1000!) ===

    # GOAL CATEGORIES (15)
    "goal.category.education": "Educación",
    "goal.category.family": "Familia",
    "goal.category.finance": "Finanzas",
    "goal.category.hobby": "Pasatiempo",
    "goal.category.home": "Hogar",
    "goal.category.relationship": "Relaciones",
    "goal.category.travel": "Viajes",
    "goal.category.work": "Trabajo",
    "goal.new": "Nuevo objetivo",
    "goal.title": "Objetivo",
    "goal.daily": "Diario",
    "goal.weekly": "Semanal",
    "goal.monthly": "Mensual",
    "goal.blank.title": "Objetivo en blanco",
    "goal.blank.description": "Empieza desde cero",

    # RELATIONSHIP TYPES (10)
    "relationship.type.partner": "Pareja",
    "relationship.type.friend": "Amigo",
    "relationship.type.family": "Familia",
    "relationship.type.colleague": "Colega",
    "relationship.health.score": "Puntuación de salud",
    "relationship.duration": "Duración",
    "relationship.together": "Juntos",
    "relationship.next.goal": "Próximo objetivo",
    "relationship.days.left.format": "%d días restantes",
    "relationship.anniversary.days": "Días hasta aniversario",

    # TRANSACTION & BALANCE (20)
    "transaction.type": "Tipo",
    "transaction.amount": "Cantidad",
    "transaction.paid": "Pagado",
    "transaction.unpaid": "No pagado",
    "transaction.i.owe": "Yo debo",
    "transaction.they.owe": "Me deben",
    "transaction.debt": "Deuda",
    "transaction.credit": "Crédito",
    "transaction.empty": "Sin transacciones",
    "transaction.add.first": "Añadir primera transacción",
    "transaction.due.today": "Vence hoy",
    "transaction.due.within.days": "Vence en %d días",
    "transaction.due.days": "Vence en días",
    "transaction.overdue.days": "Vencido por %d días",
    "balance.net.status": "Estado neto",
    "balance.balanced": "Equilibrado",
    "balance.positive": "Positivo",
    "balance.negative": "Negativo",
    "balance.debt": "Deuda",
    "balance.receivable": "Por cobrar",

    # LOVE LANGUAGES (16)
    "love.language.words": "Palabras de afirmación",
    "love.language.words.description": "Elogios verbales y palabras de aliento",
    "love.language.words.detailed": "Expresar amor a través de palabras",
    "love.language.time": "Tiempo de calidad",
    "love.language.time.description": "Pasar tiempo significativo juntos",
    "love.language.time.detailed": "Atención completa y sin distracciones",
    "love.language.gifts": "Recibir regalos",
    "love.language.gifts.description": "Regalos reflexivos y significativos",
    "love.language.gifts.detailed": "Los regalos como símbolo de amor",
    "love.language.service": "Actos de servicio",
    "love.language.service.description": "Hacer cosas para ayudar",
    "love.language.service.detailed": "Demostrar amor a través de acciones",
    "love.language.touch": "Contacto físico",
    "love.language.touch.description": "Afecto físico y cercanía",
    "love.language.touch.detailed": "El tacto como expresión de amor",
    "love.language.tips": "Consejos para aplicar",

    # DATE IDEAS (54)
    "date.ideas.title": "Ideas para citas",
    "date.ideas.random": "Idea aleatoria",
    "date.category.romantic": "Romántico",
    "date.category.adventure": "Aventura",
    "date.category.cultural": "Cultural",
    "date.category.relaxed": "Relajado",
    "date.idea.romantic.candlelight.title": "Cena a la luz de velas",
    "date.idea.romantic.candlelight.description": "Cena romántica en casa",
    "date.idea.romantic.picnic.title": "Picnic romántico",
    "date.idea.romantic.picnic.description": "Picnic en el parque",
    "date.idea.romantic.sunset.title": "Ver el atardecer",
    "date.idea.romantic.sunset.description": "Observar juntos el atardecer",
    "date.idea.romantic.stargazing.title": "Observar las estrellas",
    "date.idea.romantic.stargazing.description": "Mirar las estrellas por la noche",
    "date.idea.romantic.beach.title": "Paseo por la playa",
    "date.idea.romantic.beach.description": "Caminar por la playa al atardecer",
    "date.idea.romantic.cooking.title": "Cocinar juntos",
    "date.idea.romantic.cooking.description": "Preparar una comida especial",
    "date.idea.adventure.hiking.title": "Hacer senderismo",
    "date.idea.adventure.hiking.description": "Explorar senderos naturales",
    "date.idea.adventure.camping.title": "Acampar",
    "date.idea.adventure.camping.description": "Pasar la noche bajo las estrellas",
    "date.idea.adventure.biking.title": "Andar en bicicleta",
    "date.idea.adventure.biking.description": "Paseo en bicicleta por la ciudad",
    "date.idea.adventure.climbing.title": "Escalada",
    "date.idea.adventure.climbing.description": "Probar escalada en roca",
    "date.idea.adventure.watersports.title": "Deportes acuáticos",
    "date.idea.adventure.watersports.description": "Kayak o paddle board",
    "date.idea.adventure.escaperoom.title": "Escape room",
    "date.idea.adventure.escaperoom.description": "Resolver acertijos juntos",
    "date.idea.cultural.museum.title": "Visitar museo",
    "date.idea.cultural.museum.description": "Explorar arte e historia",
    "date.idea.cultural.theater.title": "Ver teatro",
    "date.idea.cultural.theater.description": "Disfrutar de una obra",
    "date.idea.cultural.concert.title": "Concierto",
    "date.idea.cultural.concert.description": "Escuchar música en vivo",
    "date.idea.cultural.exhibition.title": "Exposición de arte",
    "date.idea.cultural.exhibition.description": "Ver arte contemporáneo",
    "date.idea.cultural.historical.title": "Lugar histórico",
    "date.idea.cultural.historical.description": "Explorar sitios históricos",
    "date.idea.cultural.bookfair.title": "Feria del libro",
    "date.idea.cultural.bookfair.description": "Descubrir nuevos libros",
    "date.idea.relaxed.coffee.title": "Café tranquilo",
    "date.idea.relaxed.coffee.description": "Charlar en una cafetería",
    "date.idea.relaxed.movie.title": "Ver película",
    "date.idea.relaxed.movie.description": "Película en casa o cine",
    "date.idea.relaxed.spa.title": "Día de spa",
    "date.idea.relaxed.spa.description": "Relajarse juntos en el spa",
    "date.idea.relaxed.brunch.title": "Brunch",
    "date.idea.relaxed.brunch.description": "Desayuno tardío relajado",
    "date.idea.relaxed.gaming.title": "Jugar videojuegos",
    "date.idea.relaxed.gaming.description": "Juegos cooperativos",
    "date.idea.relaxed.bookcafe.title": "Librería café",
    "date.idea.relaxed.bookcafe.description": "Leer juntos en una librería",

    # MORE FRIEND DETAILS (40)
    "friend.add": "Añadir amigo",
    "friend.edit": "Editar amigo",
    "friend.delete": "Eliminar amigo",
    "friend.save": "Guardar",
    "friend.notes": "Notas",
    "friend.no.notes": "Sin notas",
    "friend.interests": "Intereses",
    "friend.favorite.things": "Cosas favoritas",
    "friend.activities.footer": "Actividades que hacen o quieren hacer juntos (separadas por comas)",
    "friend.basic.info": "Información básica",
    "friend.relationship.health": "Salud de la relación",
    "friend.communication.frequency": "Frecuencia de comunicación",
    "friend.communication.pattern": "Patrón de comunicación",
    "friend.communication.quality": "Calidad de comunicación",
    "friend.last.30.days": "Últimos 30 días",
    "friend.best.day.contact": "Mejor día para contactar",
    "friend.change.emoji": "Cambiar emoji",
    "friend.comma.separated": "Separar con comas",
    "friend.relationship.duration": "Duración de la relación",
    "friend.relationship.duration.format": "%d años",
    "friend.remaining": "Restante",
    "friend.days.remaining.format": "%d días restantes",
    "friend.days.overdue.format": "%d días vencidos",
    "friend.overdue": "Vencido",
    "friend.reminder": "Recordatorio",
    "friend.action.ai.chat": "Chat IA",
    "friend.action.mark.contacted": "Marcar como contactado",
    "friend.contact.completed": "Contacto completado",
    "friend.not.selected": "Amigo no seleccionado",
    "friend.no.history.yet": "Sin historial aún",
    "friend.last.5.meetings": "Últimos 5 encuentros",
    "friend.achievements": "Logros",
    "friend.partner.details.footer": "Detalles sobre tu pareja",
    "friend.quick.questions.loading": "Cargando preguntas rápidas...",
    "friend.mood.distribution": "Distribución de estados de ánimo",
    "friend.communication.trend.3months": "Tendencia de 3 meses",
    "friend.relationship.duration": "Duración de la relación",
    "friend.upcoming.special.dates": "Fechas especiales próximas",
    "friend.anniversary.days.remaining.format": "%d días hasta el aniversario",
    "friend.days.away.format": "%d días restantes",
    "friend.shared.interests": "Intereses compartidos",

    # WIDGET STRINGS (20)
    "widget.friends": "Amigos",
    "widget.today": "Hoy",
    "widget.call": "Llamar",
    "widget.message": "Mensaje",
    "widget.done": "Hecho",
    "widget.all.done": "Todo listo",
    "widget.all.okay": "Todo bien",
    "widget.all.up.to.date": "Todo al día",
    "widget.all.friends.contacted": "Todos contactados",
    "widget.friends.waiting": "Amigos esperando",
    "widget.time.remaining": "Tiempo restante",
    "widget.time.overdue": "Tiempo vencido",
    "widget.time.overdue.warning": "Advertencia de vencimiento",
    "widget.call.time": "Hora de llamar",
    "widget.call.time.approaching": "Se acerca la hora de llamar",
    "dashboard.claude.haiku": "Claude Haiku",
    "dashboard.notifications.loading": "Cargando notificaciones...",
    "dashboard.notifications.unread.count": "Sin leer",
    "dashboard.notifications.badge.count": "%d nuevas",
    "dashboard.achievement.ai.required": "IA requerida",

    # TIPS & CONTENT (20)
    "tips.exercise.title": "Ejercicio",
    "tips.exercise.content": "El ejercicio regular mejora el estado de ánimo",
    "tips.creative.title": "Creatividad",
    "tips.creative.content": "Expresa tu creatividad regularmente",
    "tips.social.title": "Social",
    "tips.social.content": "Mantén conexiones sociales fuertes",
    "tips.outdoor.title": "Al aire libre",
    "tips.outdoor.content": "Pasa tiempo en la naturaleza",
    "tips.relax.title": "Relajación",
    "tips.relax.content": "Toma tiempo para relajarte",
    "tips.learning.title": "Aprendizaje",
    "tips.learning.content": "Aprende algo nuevo cada día",
    "content.artist": "Artista",
    "content.author": "Autor",
    "content.director": "Director",
    "content.creator": "Creador",
    "content.developer": "Desarrollador",
    "content.writer": "Escritor",
    "content.noRating": "Sin calificación",
    "app.name": "LifeStyles",
    "app.name.life": "Life",

    # PRIVACY & TEMPLATES (15)
    "privacy.preset.strict": "Estricto",
    "privacy.preset.balanced": "Equilibrado",
    "privacy.preset.open": "Abierto",
    "privacy.knowledge.title": "Conocimiento de IA",
    "privacy.knowledge.subtitle": "Gestiona lo que la IA aprende",
    "privacy.knowledge.categories": "Categorías",
    "privacy.knowledge.deleteAll": "Eliminar todo",
    "privacy.knowledge.autoCleanup": "Limpieza automática",
    "template.all": "Todas las plantillas",
    "template.guided.writing": "Escritura guiada",
    "template.use.writing": "Usar plantilla de escritura",
    "template.usage.count": "Usado %d veces",
    "template.continue.without": "Continuar sin plantilla",
    "ai.retention.off": "Desactivado",
    "ai.retention.30days": "30 días",

    # TAGS & FILTERS (20)
    "tags.label": "Etiquetas",
    "tags.suggestions": "Sugerencias",
    "tags.frequently.used": "Usadas frecuentemente",
    "tags.selected.count": "seleccionadas",
    "tags.selected.count.format": "%d seleccionadas",
    "tag.new.title": "Nueva etiqueta",
    "tag.preview": "Vista previa",
    "tag.done": "Hecho",
    "tag.emoji.optional": "Emoji (opcional)",
    "tag.frequency": "Frecuencia",
    "tag.usage.count": "Usos",
    "tag.category.general": "General",
    "tag.category.mood": "Estado de ánimo",
    "tag.category.activity": "Actividad",
    "tag.category.topic": "Tema",
    "tag.category.priority": "Prioridad",
    "tag.category.occasion": "Ocasión",
    "filter.clear": "Limpiar filtros",
    "filter.active.count": "%d activos",
    "goals.filter.clear": "Limpiar filtros",

    # MORE COMMON (70)
    "common.total": "Total",
    "common.details": "Detalles",
    "common.complete": "Completar",
    "common.update": "Actualizar",
    "common.next": "Siguiente",
    "common.show": "Mostrar",
    "common.completed": "Completado",
    "common.month": "Mes",
    "common.notes": "Notas",
    "common.accept": "Aceptar",
    "common.basic.info": "Información básica",
    "common.days.remaining.format": "%d días restantes",
    "common.date": "Fecha",
    "common.go.to.settings": "Ir a ajustes",
    "common.urgent": "Urgente",
    "common.emoji.optional": "Emoji (opcional)",
    "common.ai.suggestion": "Sugerencia de IA",
    "common.premium.upgrade": "Actualizar a Premium",
    "common.name": "Nombre",
    "common.info": "Información",
    "common.title": "Título",
    "common.copy": "Copiar",
    "common.percentage": "Porcentaje",
    "common.premium.feature": "Característica Premium",
    "common.phone": "Teléfono",
    "common.note": "Nota",
    "common.description.optional": "Descripción (opcional)",
    "common.today.celebration": "¡Hoy!",
    "common.no.results": "Sin resultados",
    "common.not.selected": "No seleccionado",
    "mood.record.title": "Título del registro",
    "mood.record.count": "registros",
    "mood.records.count": "Registros",
    "mood.records.format": "%d registros",
    "mood.total.format": "Total: %d",
    "mood.type.display": "Tipo",
    "mood.title.value": "Valor del título",
    "mood.mini.stat.cards": "Tarjetas de estadísticas",
    "mood.next.badge": "Próxima insignia",
    "mood.streak.badges.earned": "Insignias de racha ganadas",
    "mood.streak.days.format": "Racha de %d días",
    "mood.streak.longest.format": "Racha más larga: %d días",
    "mood.heatmap.days.format": "%d días",
    "mood.heatmap.no.record": "Sin registro",
    "mood.heatmap.more": "Más",
    "mood.less": "Menos",
    "mood.correlation.empty.title": "Sin correlaciones aún",
    "mood.correlation.empty.message": "Rastrea estados de ánimo para ver patrones",
    "mood.correlation.friend.title": "Correlación con amigos",
    "mood.correlation.location.title": "Correlación con ubicaciones",
    "mood.correlation.goal.title": "Correlación con objetivos",
    "mood.correlation.meetings.format": "%d encuentros",
    "mood.correlation.data.points.format": "%d puntos de datos",
    "mood.no.records.period": "Sin registros en este período",
    "mood.generated.time": "Generado hace %@",
    "mood.generate.analysis": "Generar análisis",
    "mood.premium.long.analysis": "Análisis largo (Premium)",
    "mood.heatmap.premium.required": "Premium requerido para mapa de calor",
    "mood.30.day.heatmap": "Mapa de calor de 30 días",
    "mood.30plus.analysis": "Análisis de 30+ días",
    "mood.ai.analysis.ready": "Análisis de IA listo",
    "mood.analytics.highlights": "Destacados",
    "mood.analytics.pattern": "Patrón",
    "mood.analytics.suggestions": "Sugerencias",
    "mood.analytics.detailed.analysis": "Análisis detallado",
    "mood.track.daily.emotions": "Rastrea tus emociones diarias",
    "mood.questions": "Preguntas",
    "mood.journal.title": "Título del diario",

    # === PHASE 6.1: FINAL PUSH TO 1000 (34 keys) ===
    "achievement.unlocked.multiple": "Múltiples logros desbloqueados",
    "activity.cafe.read.book.title": "Leer un libro en el café",
    "activity.home.prepare.tomorrow.desc": "Prepara el día de mañana",
    "activity.home.relax.time.desc": "Toma tiempo para relajarte",
    "activity.home.relax.time.title": "Tiempo de relajación",
    "activity.home.short.break.desc": "Toma un descanso breve",
    "activity.home.short.break.title": "Descanso corto",
    "activity.nature.meditation.desc": "Medita en la naturaleza",
    "activity.nature.meditation.title": "Meditación en la naturaleza",
    "activity.nature.photo.desc": "Toma fotos de la naturaleza",
    "activity.nature.photo.title": "Fotografía de naturaleza",
    "activity.nature.walk.desc": "Camina en la naturaleza",
    "activity.nature.walk.title": "Paseo por la naturaleza",
    "activity.work.focus.mode.desc": "Activa modo de enfoque",
    "activity.work.focus.mode.title": "Modo de enfoque",
    "activity.work.hydrate.title": "Hidrátate",
    "activityCategory.art": "Arte",
    "activityCategory.cooking": "Cocina",
    "activityCategory.creative": "Creativo",
    "activityCategory.entertainment": "Entretenimiento",
    "activityCategory.gaming": "Videojuegos",
    "activityCategory.learning": "Aprendizaje",
    "activityCategory.music": "Música",
    "activityCategory.other": "Otro",
    "activityCategory.outdoor": "Al aire libre",
    "activityCategory.reading": "Lectura",
    "activityCategory.social": "Social",
    "activityCategory.sports": "Deportes",
    "activityCategory.travel": "Viajes",
    "activityCategory.wellness": "Bienestar",
    "ai.chat.error.fallback": "Error en el chat. Intenta de nuevo.",
    "ai.chat.friend.description.format": "Chat sobre %@",
    "Bildirim Ayarları": "Configuración de notificaciones",
    "Kayıtlı Yerler": "Lugares guardados",
}

def translate_file():
    """Translate Spanish localization file"""

    file_path = Path('LifeStyles/Resources/es.lproj/Localizable.strings')

    if not file_path.exists():
        print(f"❌ File not found: {file_path}")
        return

    print("🇪🇸 İspanyolca Çeviri Güncelleniyor - PHASE 2...")
    print(f"📁 Dosya: {file_path}")
    print(f"📝 Çeviri sayısı: {len(TRANSLATIONS)}\n")

    # Read file
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Track changes
    updated_count = 0
    not_found = []

    # Replace translations
    for key, translation in sorted(TRANSLATIONS.items()):
        # Pattern: "key" = "old_value";
        pattern = rf'^("{key}"\s*=\s*)"[^"]*";'
        replacement = rf'\1"{translation}";'

        # Check if key exists
        if re.search(pattern, content, re.MULTILINE):
            # Replace
            new_content = re.sub(pattern, replacement, content, flags=re.MULTILINE)

            if new_content != content:
                content = new_content
                updated_count += 1
                print(f"✅ {key}")
        else:
            not_found.append(key)

    # Write updated file
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

    # Summary
    print(f"\n{'='*60}")
    print(f"🎉 Phase 2 Tamamlandı!")
    print(f"✅ Güncellenen: {updated_count}/{len(TRANSLATIONS)}")
    print(f"📊 Başarı oranı: {updated_count/len(TRANSLATIONS)*100:.1f}%")

    if not_found:
        print(f"\n⚠️  Bulunamayan key'ler ({len(not_found)}):")
        for key in not_found[:15]:
            print(f"   - {key}")
        if len(not_found) > 15:
            print(f"   ... ve {len(not_found) - 15} key daha")

    print(f"\n💡 Sonraki adım:")
    print(f"   git add {file_path}")
    print(f"   git commit -m \"chore: İspanyolca çeviri Phase 2 - {updated_count} key\"")

if __name__ == '__main__':
    translate_file()
